### ISSUE TITLE
ssh from within container

### ISSUE THREAD

**Issue by fiala-sns** [OliveTin/docs.olivetin.app#17]
Tried to look for this around and did not found nothing so if it is duplicity then I as sorry.

I run into issue with ssh from within OliveTin container to docker host and keep getting error 255.
Settings: Debian 12 on RPi5 with docker compose setup.

config.yaml:
```yaml
actions:  
  - title: Restart Plex
    icon: restart
    shell: ssh user@docker-host 'docker restart plex'
    timeout: 5
```
No FW, keys copied, ssh from docker host -> localhost (it self) worked but not from OliveTin container.
Revelation came when I tried this directly from within container (docker exec -it olivetin sh) and this came up:
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes

I confirm it and then every thing started to work.
What I suggest is to add this step to action-ssh.adoc somewhere.
I am personally  new to Linux world so I am not sure if it is me being noob or if it could help somebody. 

OliveTin si awesome! :-)
