### ISSUE TITLE
Update the docker-compose.yml example

### ISSUE THREAD

**Issue by markgreene74** [OliveTin/docs.olivetin.app#34]
Hi!

First of all, thanks for OliveTin and for the excellent documentation!

I think the `docker-compose.yml` example in the [Docker Compose install](https://github.com/OliveTin/docs.olivetin.app/blob/main/modules/ROOT/pages/install/docker_compose.adoc) page needs updating.

```yml
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
(...)
```

The example contains a `version` attribute which is now deprecated and generates a warning.

```shell
gc@gc-pi:~/tmp/olivetin$ docker compose up -d
WARN[0000] /home/gc/tmp/olivetin/compose.yml: the attribute `version` is obsolete, it will
be ignored, please remove it to avoid potential confusion
gc@gc-pi:~/tmp/olivetin$ docker --version
Docker version 28.0.1, build 068a01e
```

Compose file reference:
https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete

I'd be happy to raise a PR if you accept contributions.
